CREATE TABLE nbsync_errors (
	id INT AUTO_INCREMENT PRIMARY KEY,
	event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LEVEL VARCHAR(20) NOT NULL,
	ip_address VARCHAR(45),
    sync_error VARCHAR(255)
);