CREATE TABLE dns_netbox_log (
	id INT AUTO_INCREMENT PRIMARY KEY,
	event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LEVEL VARCHAR(20) NOT NULL,
	ip_address VARCHAR(45) NOT NULL,
	netbox_name VARCHAR(255),
	dns_name VARCHAR(255)
);